
// Copyright 2021-2023 Henrik Steffen Gaßmann
//
// Distributed under the Boost Software License, Version 1.0.
//         (See accompanying file LICENSE or copy at
//           https://www.boost.org/LICENSE_1_0.txt)

#pragma once

// the configuration generated by cmake is fully optional
#if __has_include(<dplx/dlog/detail/config.hpp>)
#include <dplx/dlog/detail/config.hpp>
#endif

#if !defined(DPLX_DLOG_DISABLE_WORKAROUNDS)
#define DPLX_DLOG_DISABLE_WORKAROUNDS 0
#endif
#if !defined(DPLX_DLOG_FLAG_OUTDATED_WORKAROUNDS)
#define DPLX_DLOG_FLAG_OUTDATED_WORKAROUNDS 0
#endif

#if !defined(DPLX_DLOG_USE_BOOST_ATOMIC_REF)
#include <version>
#if __cpp_lib_atomic_ref >= 201'806L
#define DPLX_DLOG_USE_BOOST_ATOMIC_REF 0
#else
#define DPLX_DLOG_USE_BOOST_ATOMIC_REF 1
#endif
#endif
