if(POLICY CMP0056)
    cmake_policy(SET CMP0056 NEW)
endif()
if(POLICY CMP0066)
    cmake_policy(SET CMP0066 NEW)
endif()
if(POLICY CMP0067)
    cmake_policy(SET CMP0067 NEW)
endif()
if(POLICY CMP0137)
    cmake_policy(SET CMP0137 NEW)
endif()

set(CMAKE_C_STANDARD 17 CACHE STRING "C standard")
set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard")
set(CMAKE_CXX_SCAN_FOR_MODULES OFF CACHE BOOL "C++ module scanning")
