execute_process(COMMAND brew --prefix llvm@19 OUTPUT_VARIABLE BREW_LLVM_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)

set(CMAKE_C_COMPILER "${BREW_LLVM_PATH}/bin/clang")
set(CMAKE_CXX_COMPILER "${BREW_LLVM_PATH}/bin/clang++")
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.5 CACHE STRING "OSX deployment target")
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "OSX target architectures")

set(CMAKE_C_STANDARD 17 CACHE STRING "C standard")
set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard")

set(CMAKE_CXX_FLAGS_INIT "-fsized-deallocation")
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
