
entry = record / span_start / span_end

record = [
    severity,
    span_context / null,
    timestamp,
    message: str,
    fmtArgs: [* any],
    line: uint / null,
    file: tstr / null,
]

span_start = [
    id: span_context,
    parent: span_context / null,
    name: tstr,
    origin: tstr / null,
    timestamp,
]
span_end = [
    id: span_context,
    timestamp,
]

span_context = [
    trace_id,
    span_id,
]

attributes = {
    * attribute_id => any
}

attribute_id = uint / tstr

timestamp = uint
trace_id = bstr .size 16
span_id = bstr .size 8
severity = #0.0 .. #0.23
