name: GitHub Pages

on:
  push:
    branches:
      - master
      - "releases/v*"
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: docs/requirements.txt

      - name: Install dependencies
        run: python3 -m pip install -r ./docs/requirements.txt

      - if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/release/v')
        run: sphinx-build docs build/html

      - if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/v')
        run: sphinx-multiversion docs build/html

      - if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/v')
        run: cp ./docs/root.html ./build/html/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
